### ISSUE TITLE
Build of client doesn't run

### ISSUE THREAD

**Issue by RainePark** [HackintoshwithUbuntu/Python-Chat-App#1]
Gives error when attempting to open the compiled exe file in /dist

![image](https://user-images.githubusercontent.com/27046649/223341024-ab0cdf82-4493-40ea-8342-47a290caf2de.png)

Traceback (most recent call last):
  File "Client.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "eel\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by HackintoshwithUbuntu** [comment]
Hi @RainePark 
For the time being please consider using the python code. This may be an issue with a newer version of PyInstaller or Eel. I will look into the issue in the coming weeks
